apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  template:
    spec:
      containers:
      - name: ubuntu-server
        image: ubuntu:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["echo 'Hello World, this is DEV mode' && sleep infinity"]
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi